# Site settings
name: myBlog
email: 602505401@qq.com
author: dianbo
url: http://www.bo-study.com
resume_site: http://www.bo-study.com
github: https://github.com/bo07997/
baseurl: "/"
description: Actually, less is more!
meta_description: 康志华;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: bo07997

# Build settings
markdown: kramdown

baidu_analysis: 77e38020c55d47f90b365285973c1a06


theme: jekyll-theme-merlot